env:
  browser: true
  es2021: true
  node: true
  jest: true

extends: 
  - "airbnb-base"
  - "plugin:jest/recommended"

overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  import/extensions: 0
  no-param-reassign: 0
  no-console: 0
